version: '2'

services:

  app:
    build: .
    volumes:
      - ./Hausarbeit/target:/app
    ports:
      - '80:8080'
      - '48:4848'
    restart: always
#    command: >
#      bash -c "
#        cp /app/Hausarbeit-1.0-SNAPSHOT.war /app/Hausarbeit.war &&
#        asadmin deploy /app/Hausarbeit"
#entrypoint: |
#      bash -c 'bash -s <<EOF
#      trap "break;exit" SIGHUP SIGINT SIGTERM
#      while /bin/true; do
#        su -s "/bin/bash" -c "/usr/local/bin/php /var/www/html/console core:archive" www-data
#        sleep 3600
#      done
#-      EOF'--